name: uvccamera_example
description: "Demonstrates how to use the uvccamera plugin."
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  uvccamera:
    path: ../
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  google_mlkit_pose_detection: ^0.13.0
  google_mlkit_commons: ^0.9.0
  path_provider: ^2.1.5
  image: ^4.1.32

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
